var searchData=
[
  ['secantmethod_0',['SecantMethod',['../classOptimization_1_1SecantMethod.html',1,'Optimization']]],
  ['simulatedannealing_1',['SimulatedAnnealing',['../classOptimization_1_1SimulatedAnnealing.html',1,'Optimization']]],
  ['spherefunction_2',['SphereFunction',['../structOptimization_1_1Tests_1_1SphereFunction.html',1,'Optimization::Tests']]],
  ['sqpsolver_3',['SQPSolver',['../classOptimization_1_1SQPSolver.html',1,'Optimization']]],
  ['staticmatrix_4',['StaticMatrix',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20kkt_5fsize_20_3e_5',['StaticMatrix&lt; double, KKT_Size &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20kkt_5fsize_2c_20kkt_5fsize_20_3e_6',['StaticMatrix&lt; double, KKT_Size, KKT_Size &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fcons_20_3e_7',['StaticMatrix&lt; double, N_cons &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fcons_2c_20n_5fvars_20_3e_8',['StaticMatrix&lt; double, N_cons, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5feq_20_3e_9',['StaticMatrix&lt; double, N_eq &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5feq_2c_20n_5fvars_20_3e_10',['StaticMatrix&lt; double, N_eq, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fineq_20_3e_11',['StaticMatrix&lt; double, N_ineq &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fineq_2c_20n_5fvars_20_3e_12',['StaticMatrix&lt; double, N_ineq, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fvars_20_3e_13',['StaticMatrix&lt; double, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fvars_2c_20n_5fvars_20_3e_14',['StaticMatrix&lt; double, N_vars, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nu_20_3e_15',['StaticMatrix&lt; double, Nu &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nx_20_3e_16',['StaticMatrix&lt; double, Nx &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20int_2c_20maxnnz_20_3e_17',['StaticMatrix&lt; int, MaxNNZ &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20int_2c_20rows_2b1_20_3e_18',['StaticMatrix&lt; int, Rows+1 &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20t_2c_20maxnnz_20_3e_19',['StaticMatrix&lt; T, MaxNNZ &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticsparsematrix_20',['StaticSparseMatrix',['../classOptimization_1_1StaticSparseMatrix.html',1,'Optimization']]],
  ['strongbacktrackinglinesearch_21',['StrongBacktrackingLineSearch',['../classOptimization_1_1StrongBacktrackingLineSearch.html',1,'Optimization']]],
  ['strongwolfetest_22',['StrongWolfeTest',['../classStrongWolfeTest.html',1,'']]]
];
