var searchData=
[
  ['secantmethod_0',['SecantMethod',['../classOptimization_1_1SecantMethod.html',1,'Optimization']]],
  ['simulatedannealing_1',['SimulatedAnnealing',['../classOptimization_1_1SimulatedAnnealing.html',1,'Optimization']]],
  ['sparseipmqpsolver_2',['SparseIPMQPSolver',['../classOptimization_1_1SparseIPMQPSolver.html',1,'Optimization']]],
  ['sparseipmqpsolver_3c_20n_5fvars_2c_20n_5fineq_2c_20n_5fvars_20_2an_5fvars_2c_20n_5fvars_20_2a8_20_3e_3',['SparseIPMQPSolver&lt; N_vars, N_ineq, N_vars *N_vars, N_vars *8 &gt;',['../classOptimization_1_1SparseIPMQPSolver.html',1,'Optimization']]],
  ['spherefunction_4',['SphereFunction',['../structOptimization_1_1Tests_1_1SphereFunction.html',1,'Optimization::Tests']]],
  ['sqpsolver_5',['SQPSolver',['../classOptimization_1_1SQPSolver.html',1,'Optimization']]],
  ['staticmatrix_6',['StaticMatrix',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20kkt_5fsize_20_3e_7',['StaticMatrix&lt; double, KKT_Size &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20kkt_5fsize_2c_20kkt_5fsize_20_3e_8',['StaticMatrix&lt; double, KKT_Size, KKT_Size &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20maxnnz_20_3e_9',['StaticMatrix&lt; double, MaxNNZ &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fcons_20_3e_10',['StaticMatrix&lt; double, N_cons &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fcons_2c_20n_5fvars_20_3e_11',['StaticMatrix&lt; double, N_cons, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5feq_20_3e_12',['StaticMatrix&lt; double, N_eq &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5feq_2c_20n_5fvars_20_3e_13',['StaticMatrix&lt; double, N_eq, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fineq_20_3e_14',['StaticMatrix&lt; double, N_ineq &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fineq_2c_20n_5fvars_20_3e_15',['StaticMatrix&lt; double, N_ineq, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fvars_20_3e_16',['StaticMatrix&lt; double, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20n_5fvars_2c_20n_5fvars_20_3e_17',['StaticMatrix&lt; double, N_vars, N_vars &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nu_20_3e_18',['StaticMatrix&lt; double, Nu &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nu_2c_20nu_20_3e_19',['StaticMatrix&lt; double, Nu, Nu &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nu_2c_20nx_20_3e_20',['StaticMatrix&lt; double, Nu, Nx &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nx_20_3e_21',['StaticMatrix&lt; double, Nx &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nx_2c_20nu_20_3e_22',['StaticMatrix&lt; double, Nx, Nu &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20double_2c_20nx_2c_20nx_20_3e_23',['StaticMatrix&lt; double, Nx, Nx &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20int_2c_20maxnnz_20_3e_24',['StaticMatrix&lt; int, MaxNNZ &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20int_2c_20rows_2b1_20_3e_25',['StaticMatrix&lt; int, Rows+1 &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticmatrix_3c_20t_2c_20maxnnz_20_3e_26',['StaticMatrix&lt; T, MaxNNZ &gt;',['../classStaticMatrix.html',1,'']]],
  ['staticsparsematrix_27',['StaticSparseMatrix',['../classOptimization_1_1StaticSparseMatrix.html',1,'Optimization']]],
  ['staticsparsematrix_3c_20double_2c_20n_5fineq_2c_20n_5fvars_2c_20maxnnz_5fa_20_3e_28',['StaticSparseMatrix&lt; double, N_ineq, N_vars, MaxNNZ_A &gt;',['../classOptimization_1_1StaticSparseMatrix.html',1,'Optimization']]],
  ['staticsparsematrix_3c_20double_2c_20n_5fvars_2c_20n_5fvars_2c_20maxnnz_5fp_20_3e_29',['StaticSparseMatrix&lt; double, N_vars, N_vars, MaxNNZ_P &gt;',['../classOptimization_1_1StaticSparseMatrix.html',1,'Optimization']]],
  ['strongbacktrackinglinesearch_30',['StrongBacktrackingLineSearch',['../classOptimization_1_1StrongBacktrackingLineSearch.html',1,'Optimization']]],
  ['strongwolfetest_31',['StrongWolfeTest',['../classStrongWolfeTest.html',1,'']]]
];
